//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeList
    {
        public int No_ { get; set; }
        public string Injection_Code { get; set; }
        public string Machine_No_ { get; set; }
        public string Machine { get; set; }
        public string Cycle_Time { get; set; }
        public string Cavity { get; set; }
        public string Manpower { get; set; }
        public string Resin { get; set; }
        public string Resin_Code { get; set; }
        public string Weight { get; set; }
        public string Another_Code { get; set; }
        public string ItemName { get; set; }
    }
}
