//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_Injection
    {
        public int No_ { get; set; }
        public string Code { get; set; }
        public Nullable<int> So_May { get; set; }
        public string Trong_Luong_May { get; set; }
        public Nullable<double> C_Good { get; set; }
        public Nullable<int> Ke_Hoach { get; set; }
        public Nullable<int> Ke_Hoach_Bo_Sung { get; set; }
        public Nullable<double> Manpower { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<double> Cycle_time { get; set; }
        public Nullable<int> Cavity { get; set; }
        public Nullable<double> Capa { get; set; }
        public Nullable<int> Balance_Plan { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Requirements { get; set; }
        public Nullable<double> Plan_Time_D_ { get; set; }
        public Nullable<int> Plan_D_ { get; set; }
        public Nullable<int> Good_D_ { get; set; }
        public Nullable<int> NG_D_ { get; set; }
        public Nullable<double> C_NG { get; set; }
        public Nullable<double> C_Plan_Time_N_ { get; set; }
        public Nullable<int> Plan_N_ { get; set; }
        public Nullable<int> Good_N_ { get; set; }
        public Nullable<int> NG_N_ { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public string Week { get; set; }
        public string ID_PlanTimeDem { get; set; }
        public string ID_PlanTimeNgay { get; set; }
        public string PSI { get; set; }
        public string Statuss { get; set; }
        public Nullable<int> plandemtemp { get; set; }
        public Nullable<double> plantimedemtemp { get; set; }
        public Nullable<int> planngaytemp { get; set; }
        public Nullable<double> plantimengaytemp { get; set; }
        public string ID_PlanDem { get; set; }
        public string ID_PlanNgay { get; set; }
        public string Html_PlanTimeDem { get; set; }
        public string Html_PlanTimeNgay { get; set; }
        public Nullable<bool> FlagDem { get; set; }
        public Nullable<bool> FlagNgay { get; set; }
        public string ID_ValidateDem { get; set; }
        public string ID_ValidateNgay { get; set; }
        public string ID_Balance { get; set; }
        public string ID_KHBS { get; set; }
        public string Html_SoMay { get; set; }
        public Nullable<int> STT { get; set; }
        public string ItemName { get; set; }
    }
}
