//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaSanXuatThieu
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SoThieuCaDem { get; set; }
        public Nullable<int> SoThieuCaNgay { get; set; }
        public Nullable<int> SoMay { get; set; }
        public string Week { get; set; }
        public string PSI { get; set; }
        public Nullable<bool> FlagDem { get; set; }
        public Nullable<bool> FlagNgay { get; set; }
    }
}
