//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlanEntities : DbContext
    {
        public PlanEntities()
            : base("name=PlanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PicklistVatTu> PicklistVatTus { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Assy_PSI_Shortage> Assy_PSI_Shortage { get; set; }
        public virtual DbSet<PSI_WM_REF> PSI_WM_REF { get; set; }
        public virtual DbSet<Production_Result> Production_Result { get; set; }
        public virtual DbSet<Plan_Week> Plan_Week { get; set; }
        public virtual DbSet<KetQuaSanXuatThieu> KetQuaSanXuatThieux { get; set; }
        public virtual DbSet<ResinStock> ResinStocks { get; set; }
        public virtual DbSet<SummaryByProduct> SummaryByProducts { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<MailServer> MailServers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MailVerify> MailVerifies { get; set; }
        public virtual DbSet<CodeList> CodeLists { get; set; }
        public virtual DbSet<DA_Injection> DA_Injection { get; set; }
        public virtual DbSet<PSI_V_C> PSI_V_C { get; set; }
    
        public virtual int Delete_Stock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Stock");
        }
    
        public virtual ObjectResult<Nullable<int>> SumAssy(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SumAssy", codeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_Require_Assy(string code_assy, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_Require_Assy", code_assyParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_Require_VC(string code_assy, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_Require_VC", code_assyParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_Require_Ref(string code_assy, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_Require_Ref", code_assyParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_Require_DA(string code_assy, string week)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var weekParameter = week != null ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_Require_DA", code_assyParameter, weekParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_PLD_DA(string code_assy, string week)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var weekParameter = week != null ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_PLD_DA", code_assyParameter, weekParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sum_PLN_DA(string code_assy, string week)
        {
            var code_assyParameter = code_assy != null ?
                new ObjectParameter("code_assy", code_assy) :
                new ObjectParameter("code_assy", typeof(string));
    
            var weekParameter = week != null ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sum_PLN_DA", code_assyParameter, weekParameter);
        }
    
        public virtual ObjectResult<GetViewPlan_Result> GetViewPlan(string week, string status)
        {
            var weekParameter = week != null ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetViewPlan_Result>("GetViewPlan", weekParameter, statusParameter);
        }
    
        public virtual int Delete_ResinStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_ResinStock");
        }
    }
}
