//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryByProduct
    {
        public int STT { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Mc { get; set; }
        public string ResinCode { get; set; }
        public string Resin { get; set; }
        public Nullable<double> MixRate { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string Week { get; set; }
    }
}
