//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string User1 { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string BoPhan { get; set; }
        public Nullable<int> NumberPhone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public string GroupID { get; set; }
        public Nullable<bool> VIEW_USER { get; set; }
        public Nullable<bool> LAP_KEHOACH { get; set; }
        public Nullable<bool> EDIT_KEHOACH { get; set; }
        public Nullable<bool> XUAT_EXCEL { get; set; }
        public Nullable<bool> ADD_STOCK { get; set; }
        public Nullable<bool> DELETE_STOCK { get; set; }
        public Nullable<bool> ADD_RESINSTOCK { get; set; }
        public Nullable<bool> DELETE_RESINSTOCK { get; set; }
        public Nullable<bool> EDIT_STOCK { get; set; }
        public Nullable<bool> EDIT_RESINSTOCK { get; set; }
        public Nullable<bool> EDIT_KQSX { get; set; }
        public Nullable<bool> NHAP_KQSX { get; set; }
        public Nullable<bool> ADD_CODELIST { get; set; }
        public Nullable<bool> ADD_PICKLISTVATTU { get; set; }
        public Nullable<bool> IMPORT_PSI { get; set; }
        public Nullable<bool> IMPORT_STOCK { get; set; }
        public Nullable<bool> IMPORT_RESINSTOCK { get; set; }
        public Nullable<bool> EDIT_CODELIST { get; set; }
        public Nullable<bool> EDIT_PICKLISTVATTU { get; set; }
    }
}
